---
Name: lifeboat_routes
After:
- '#rootroutes'
- '#coreroutes'
- '#adminroutes'
---
SilverStripe\Control\Director:
  rules:
    'objects_controller_ab': 'ObjectsControllerAB'
    'objects_controller_ac': 'ObjectsControllerAC'

